
jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360

  variables:
    CONFIG: linux_cuda_compiler_versionNonepython3.6.____cpython
    R_CONFIG: linux_64_r_base3.6
    ARROW_VERSION: 3.1.0.dev552
    UPLOAD_PACKAGES: False

  steps:
  - script: |
          git clone --no-checkout https://github.com/kszucs/arrow arrow
          git -C arrow fetch -t https://github.com/kszucs/arrow crossbow-to-archery
          git -C arrow checkout FETCH_HEAD
          git -C arrow submodule update --init --recursive
        displayName: Clone arrow


  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    displayName: Configure binfmt_misc
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))

  - task: CondaEnvironment@1
    inputs:
      packageSpecs: 'anaconda-client shyaml'
      installOptions: '-c conda-forge'
      updateConda: false

  - script: |
      mkdir build_artifacts
      CI=azure arrow/dev/tasks/conda-recipes/run_docker_build.sh $(pwd)/build_artifacts
    displayName: Run docker build

  - script: pip install -e arrow/dev/archery[crossbow]
        displayName: Install Crossbow
      - script: |
          archery crossbow \
            --queue-path $(pwd) \
            --queue-remote https://github.com/ursacomputing/crossbow.git \
            upload-artifacts \
            --sha build-138-azure-conda-linux-gcc-py36-cpu-r36 \
            --tag build-138-azure-conda-linux-gcc-py36-cpu-r36 \
            --pattern "build_artifacts/linux-64/*.tar.bz2"
        env:
          CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
        displayName: Upload packages as a GitHub release


