jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360

  steps:
  - script: |
      git clone --no-checkout https://github.com/pitrou/arrow.git arrow
      git -C arrow fetch -t https://github.com/pitrou/arrow.git ARROW-15898-conda-clean
      git -C arrow checkout FETCH_HEAD
      git -C arrow submodule update --init --recursive
    displayName: Clone arrow

  - script: |
      conda install -y -c conda-forge pandas anaconda-client packaging
    displayName: Install requirements

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate base
      python3 arrow/dev/tasks/conda-recipes/clean.py FORCE
    displayName: Delete outdated packages
