
jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360

  variables:
    CONFIG: linux_64_cuda_compiler_version10.2numpy1.17python3.7.____cpython
    R_CONFIG: 
    ARROW_VERSION: 7.0.0.dev141
    UPLOAD_PACKAGES: False

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    displayName: Configure binfmt_misc
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))

  - script: |
      git clone --no-checkout https://github.com/bkmgit/arrow.git arrow
      git -C arrow fetch -t https://github.com/bkmgit/arrow.git bkmgit-update-dependencies
      git -C arrow checkout FETCH_HEAD
      git -C arrow submodule update --init --recursive
    displayName: Clone arrow


  - task: CondaEnvironment@1
    inputs:
      packageSpecs: 'anaconda-client shyaml'
      installOptions: '-c conda-forge'
      updateConda: false

  - script: |
      mkdir build_artifacts
      CI=azure arrow/dev/tasks/conda-recipes/run_docker_build.sh $(pwd)/build_artifacts
    displayName: Run docker build

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: pip install -e arrow/dev/archery[crossbow-upload]
    displayName: Install Crossbow
  - bash: |
      archery crossbow \
        --queue-path $(pwd) \
        --queue-remote https://github.com/ursacomputing/crossbow \
        upload-artifacts \
        --sha actions-1164-azure-conda-linux-gcc-py37-cuda \
        --tag actions-1164-azure-conda-linux-gcc-py37-cuda \
        "build_artifacts/*/*.tar.bz2"
    env:
      CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
    displayName: Upload packages as a GitHub release

  