jobs:
- job: linux
  pool:
    vmImage: ubuntu-18.04
  timeoutInMinutes: 360

  steps:
  - script: |
      git clone --no-checkout https://github.com/apache/arrow arrow
      git -C arrow fetch -t https://github.com/apache/arrow apache-arrow-4.0.1
      git -C arrow checkout FETCH_HEAD
      git -C arrow submodule update --init --recursive
    displayName: Clone arrow

  - script: |
      conda install -y -c conda-forge pandas anaconda-client packaging
    displayName: Install requirements

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate base
      python3 arrow/dev/tasks/conda-recipes/clean.py     displayName: Delete outdated packages
