
jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360

  variables:
    CONFIG: linux_aarch64_numpy1.17python3.6.____cpython
    R_CONFIG: 
    ARROW_VERSION: 5.0.0.dev414
    UPLOAD_PACKAGES: False

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    displayName: Configure binfmt_misc
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))

  - script: |
      git clone --no-checkout https://github.com/apache/arrow arrow
      git -C arrow fetch -t https://github.com/apache/arrow master
      git -C arrow checkout FETCH_HEAD
      git -C arrow submodule update --init --recursive
    displayName: Clone arrow


  - task: CondaEnvironment@1
    inputs:
      packageSpecs: 'anaconda-client shyaml'
      installOptions: '-c conda-forge'
      updateConda: false

  - script: |
      mkdir build_artifacts
      CI=azure arrow/dev/tasks/conda-recipes/run_docker_build.sh $(pwd)/build_artifacts
    displayName: Run docker build

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: pip install -e arrow/dev/archery[crossbow]
    displayName: Install Crossbow
  - bash: |
      archery crossbow \
        --queue-path $(pwd) \
        --queue-remote https://github.com/ursacomputing/crossbow \
        upload-artifacts \
        --sha nightly-2021-07-14-0-azure-conda-linux-gcc-py36-arm64 \
        --tag nightly-2021-07-14-0-azure-conda-linux-gcc-py36-arm64 \
        "build_artifacts/*/*.tar.bz2"
    env:
      CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
    displayName: Upload packages as a GitHub release

  - task: CondaEnvironment@1
    inputs:
      packageSpecs: 'anaconda-client'
      installOptions: '-c conda-forge'
      updateConda: no
  - script: |
      conda install -y anaconda-client
      anaconda -t $(CROSSBOW_ANACONDA_TOKEN) upload --force build_artifacts/*/*.tar.bz2
    displayName: Upload packages to Anaconda
