name: M1 R Test

on: workflow_dispatch

jobs:
  test:
    runs-on: devops-managed
    steps:
        - name: Detect M1
          run: |
            if [[ $(uname -m) == 'arm64' ]]; then
              echo "On M1"
            fi
            arch -arm64 brew install rclone
