name: Report packaging

on:
  push:
    paths:
      - '.github/workflows/nightly_packaging_report.yml'
  schedule:
    - cron: '0 14 * * *'

jobs:
  nightly_packaging_report:
    uses: ursacomputing/crossbow/.github/workflows/report.yml@master
    with:
      report_type: packaging
    secrets:
      CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
      CROSSBOW_SMTP_USER: ${{ secrets.CROSSBOW_SMTP_USER }}
      CROSSBOW_SMTP_PASSWORD: ${{ secrets.CROSSBOW_SMTP_PASSWORD }}
      CROSSBOW_ZULIP_WEBHOOK: ${{ secrets.CROSSBOW_ZULIP_WEBHOOK }}
      CROSSBOW_SLACK_WEBHOOK: ${{ secrets.CROSSBOW_SLACK_WEBHOOK }}
