name: Report releases

on:
  push:
    paths:
      - '.github/workflows/nightly_releases_report.yml'
  schedule:
    - cron: '0 20 * * *'

jobs:
  nightly_releases_report:
    uses: ursacomputing/crossbow/.github/workflows/report.yml@master
    with:
      report_type: releases
    secrets:
      CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
      CROSSBOW_SMTP_USER: ${{ secrets.CROSSBOW_SMTP_USER }}
      CROSSBOW_SMTP_PASSWORD: ${{ secrets.CROSSBOW_SMTP_PASSWORD }}
