name: Submit

on:
  schedule:
    - cron: '0 6 * * *'

jobs:

  nightly-submit:
    name: Submit Nightly Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Arrow
        shell: bash
        run: git clone https://github.com/apache/arrow
      - name: Checkout Crossbow
        shell: bash
        run: git clone https://github.com/ursacomputing/crossbow
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"
      - name: Install Archery
        shell: bash
        run: pip install -e dev/archery[crossbow]
      - name: Submit Nightlies
        shell: bash
        env:
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
        run: |
          archery crossbow submit --job-prefix nightly-$(date -I) --group nightly
