name: Report tests

on:
  push:
    paths:
      - '.github/workflows/nightly_tests_report.yml'
  schedule:
    - cron: '0 8 * * *'

jobs:
  nightly_tests_report:
    uses: ursacomputing/crossbow/.github/workflows/report.yml@master
    with:
      report_type: tests
    secrets:
      CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
      CROSSBOW_SMTP_USER: ${{ secrets.CROSSBOW_SMTP_USER }}
      CROSSBOW_SMTP_PASSWORD: ${{ secrets.CROSSBOW_SMTP_PASSWORD }}