name: Report

on:
  push:
    paths:
      - '.github/workflows/nightly_report.yml'
  schedule:
    - cron: '0 10 * * *'

jobs:

  nightly-report:
    name: Send Nightly Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Arrow
        shell: bash
        run: git clone https://github.com/apache/arrow
      - name: Checkout Crossbow
        shell: bash
        run: git clone https://github.com/ursacomputing/crossbow
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"
      - name: Install Archery
        shell: bash
        run: pip install -e arrow/dev/archery[crossbow]
      - name: Send Report
        shell: bash
        env:
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
          CROSSBOW_REPORT_SMTP_USER: ${{ secrets.CROSSBOW_SMTP_USER }}
          CROSSBOW_REPORT_SMTP_PASSWORD: ${{ secrets.CROSSBOW_SMTP_PASSWORD }}
        run: |
          job_prefix=nightly-$(date -I)
          job_id=$(archery crossbow latest-prefix ${job_prefix})
          echo "Sending report for job ${job_id}..."
          archery crossbow report \
            --send \
            --sender-name Crossbow \
            --sender-email 'crossbow@ursalabs.org' \
            --recipient-email 'dev@arrow.apache.org' \
            ${job_id}
