name: Prune Branches

on:
  push:
    paths:
      - '.github/workflows/prune_branches.yml'
  schedule:
    - cron: '0 12 * * *'

jobs:
  remove:
    name: Remove Old Branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crossbow
        uses: actions/checkout@v2
      - name: Delete Branches
        env:
          DRY_RUN: 0
        shell: bash
        run: ./delete_old_branches.sh "428 days ago"
